DROP DATABASE IF EXISTS gallery;
CREATE DATABASE gallery;
USE gallery;

DROP TABLE IF EXISTS images;
CREATE TABLE images (
    id SERIAL PRIMARY KEY,
    `name` VARCHAR(150) NOT NULL UNIQUE,
    `url` VARCHAR(255) UNIQUE NOT NULL
);